#
# CMake file for the masked occlusion culling library
#
set(CMAKE_SUPPRESS_REGENERATION true)
option(USE_AVX512 "Enable experimental AVX-512 support" OFF)
set(CMAKE_CONFIGURATION_TYPES Debug Release)

set(MOC_AVX512_FILES MaskedOcclusionCullingAVX512.cpp)
set(MOC_AVX2_FILES MaskedOcclusionCullingAVX2.cpp)
set(MOC_SSE_FILES MaskedOcclusionCulling.cpp CullingThreadpool.cpp)
set(MOC_OPEN_SPACE_FILES OpenSpaceRasterizer.cpp)
set(MOC_INCLUDE_FILES MaskedOcclusionCulling.h CullingThreadpool.h CompilerSpecific.inl MaskedOcclusionCullingCommon.inl OpenSpaceRasterizer.h)
set(MOC_FILES ${MOC_AVX512_FILES} ${MOC_AVX2_FILES} ${MOC_SSE_FILES} ${MOC_OPEN_SPACE_FILES} ${MOC_INCLUDE_FILES})

if(MSVC)
    if(MSVC_VERSION LESS 1900)
        set(CMAKE_CXX_FLAGS "-std=c++11")
    endif()
else()
    set(CMAKE_CXX_FLAGS "-std=c++11 -m64")
endif()

if(MSVC)
    if(USE_AVX512)
        set_source_files_properties(${MOC_AVX512_FILES} PROPERTIES COMPILE_FLAGS "-DUSE_AVX512=1 /arch:AVX2")
    else()
        set_source_files_properties(${MOC_AVX512_FILES} PROPERTIES COMPILE_FLAGS "/arch:AVX2")
    endif()
    set_source_files_properties(${MOC_AVX2_FILES} PROPERTIES COMPILE_FLAGS "/arch:AVX2")
else()
    if(USE_AVX512)
        set_source_files_properties(${MOC_AVX512_FILES} PROPERTIES COMPILE_FLAGS "-DUSE_AVX512=1 -mavx512f -mavx512bw -mavx512dq -mavx2 -mfma -msse4.1")
    else()
        set_source_files_properties(${MOC_AVX512_FILES} PROPERTIES COMPILE_FLAGS "-mavx2 -mfma -msse4.1")
    endif()
    set_source_files_properties(${MOC_AVX2_FILES} PROPERTIES COMPILE_FLAGS "-mavx2 -mfma -msse4.1")
    set_source_files_properties(${MOC_SSE_FILES} PROPERTIES COMPILE_FLAGS "-msse4.1 -mxsave")
endif()

add_library(MaskedOcclusionCulling ${MOC_FILES})
target_include_directories(MaskedOcclusionCulling PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
